FROM pytorch/pytorch:latest

COPY . /app
WORKDIR /app
RUN apt-get update -y && apt-get install -y vim

RUN apt-get install git -y && apt install git -y

RUN pip3 install -r requirements.txt

RUN git clone https://huggingface.co/beomi/llama-2-ko-7b

WORKDIR /app/llama-2-ko-7b
RUN apt-get install git-lfs -y 
RUN git lfs fetch

WORKDIR /app


RUN nohup flask run --host=0.0.0.0 --port=8000 &

