# nginx-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  restartPolicy: Never
  containers:
    - name: nginx-container
      image: "python:3.10"
      command: ["sh", "-c"]
      args:
        [
          "apt-get update && apt-get upgrade -y && cd /dataset/llm_fine_tuning && git pull && git checkout yw_docker && pip install -r requirements.txt && cd ./train && python train.py &&  while true; do sleep 30; done;",
        ]
      resources:
        requests:
          cpu: 28
          memory: "112Gi"
          nvidia.com/gpu: 1
        limits:
          cpu: 28
          memory: "112Gi"
          nvidia.com/gpu: 1
      volumeMounts:
        - mountPath: "/dataset"
          name: nginx-pv
  volumes:
    - name: nginx-pv
      persistentVolumeClaim:
        claimName: llama-2-7b-pvc
